version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=db
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: nest-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
