# Dockerfile
FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install migrate mongo
RUN npm install -g migrate-mongo

# Copy app source code
COPY . .

# Build the app
RUN npm run build

# Expose app port
EXPOSE 3000

# Run the app
CMD ["npm", "run", "start:dev"]
